//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Rest__API.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public int UId { get; set; }
        public string Feedback1 { get; set; }
    [JsonIgnore,XmlIgnore]
        public virtual UserRegistration UserRegistration { get; set; }
    }
}
