//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend_Rest__API.Models
{
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Tbl_Cart
    {
        List<Link> links = new List<Link>();
        public int CartId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> CartStatusId { get; set; }
        public List<Link> Links
        {
            get { return links; }

        }
        [JesonIgnore, XmlIgnore]
        public virtual Tbl_Product Tbl_Product { get; set; }
    }
}
